version: 0.2
phases:
  build: 
    commands:
      - sam build
      - sam package --template-file template.yml --s3-bucket lambdas-hw2 --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml