AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Python file including external library changed again
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Index.lambda_handler
      Runtime: python3.8
      FunctionName: HW2-LF2-Cloud
      CodeUri: ./src #Directory the source file is